# Multi-stage build for all frontend images

FROM mhart/alpine-node:16 AS frontend-base
# install dependencies
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json /app/frontend/
# Copy all local files into the image.
COPY /frontend /app/frontend
WORKDIR /app/frontend
RUN npm install --only=prod
RUN npm run build

###
# Only copy over the Node pieces we need
###
FROM mhart/alpine-node:slim-14 AS frontend
COPY --from=frontend-base /app /app
WORKDIR /app/frontend
EXPOSE $PORT
ENV NODE_OPTIONS="--max-old-space-size=1024"
CMD ["node", "./build"]
