version: "3.7"

services:
  master:
    build:
      context: .
      target: locust
    ports:
     - "8089:8089"
    volumes:
      - ./api:/srv/api
      - ./static:/srv/static
      - ./migrations:/srv/migrations
      - ./tests:/srv/tests
      - ./data/test_assets:/srv/data/test_assets
      - ./data/test_gallery:/srv/data/test_gallery
      - ./backend.py:/srv/backend.py
      - ./config.py:/srv/config.py
      - ./config.json:/srv/config.json
    environment:
      - SERVER_URL=
      - WEBDRIVER_URL=http://chrome:4444/wd/hub
    command: locust -f /srv/tests/locustfile.py --master -H http://master:8089

  chrome:
    image: selenium/standalone-chrome:4.7.2-20221219
    shm_size: '2gb'
    environment:
      - START_XVFB=false
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=5
      - JAVA_OPTS=-XX:ActiveProcessorCount=5
    networks:
      - default
    deploy:
      replicas: 1
    ports:
      - "4444:4444"

  worker:
    build:
      context: .
      target: locust
    depends_on:
      - master
      - chrome
    volumes:
      - ./api:/srv/api
      - ./static:/srv/static
      - ./migrations:/srv/migrations
      - ./tests:/srv/tests
      - ./data/test_assets:/srv/data/test_assets
      - ./data/test_gallery:/srv/data/test_gallery
      - ./backend.py:/srv/backend.py
      - ./config.py:/srv/config.py
      - ./config.json:/srv/config.json
    environment:
      - SERVER_URL=h
      - WEBDRIVER_URL=http://chrome:4444/wd/hub
    command: locust -f /srv/tests/locustfile.py --worker --master-host master
