# Multi-stage build for all frontend images

FROM mhart/alpine-node:14 AS frontend-base
# install dependencies
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json /app/frontend/
# Copy all local files into the image.
COPY /frontend/src /app/frontend/src
COPY /frontend/.env /app/frontend/.env
COPY /frontend/static /app/frontend/static
COPY /frontend/jsconfig.json /app/frontend/jsconfig.json
COPY /frontend/svelte.config.js /app/frontend/svelte.config.js
#COPY /frontend/svelte.config.js /app/frontend/svelte.config.cjs
WORKDIR /app/frontend
RUN npm install --only=prod
#RUN node node_modules/esbuild/install.js
RUN npm run build
###
# Only copy over the Node pieces we need
###
FROM mhart/alpine-node:slim-14 AS frontend
COPY --from=frontend-base /app /app
WORKDIR /app/frontend
EXPOSE $PORT
ENV NODE_OPTIONS="--max-old-space-size=1024"
CMD ["node", "./build"]
