# Multi-stage build for all images

# base - os and basic requirements
FROM python:3.10-slim as base
# Apply global configs
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV SERVER_MODE base
WORKDIR /srv
# Get requirements
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt


# api - flask backend api
FROM base AS api
# Get api files
COPY core core
COPY api api
COPY migrations migrations
COPY config.py .
COPY config.json .
COPY backend.py .
COPY boot.sh .
ENV FLASK_APP backend.py
ENV SERVER_MODE api
EXPOSE $PORT
CMD ["sh", "boot.sh"]


# host - use for globally-scoped processes like testing
FROM api AS host
ENV SERVER_MODE host
# Get the rest of the files
COPY tests tests


FROM host as locust
ENV SERVER_MODE locust
