# Multi-stage build for all images

# base - os and basic requirements
FROM python:3.10-slim as base
# Apply global configs
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV SERVER_MODE base
WORKDIR /srv
## Get add-apt-repository
#RUN apt update && apt install -y software-properties-common
## Install all other OS packages
#RUN apt install -y \
#    iputils-ping \
#    poppler-utils \
#    software-properties-common \
#    libwebp-dev \
#    libjpeg62-turbo-dev \
#    libpng-dev libxpm-dev \
#    libfreetype6-dev \
#    gcc \
#    gnupg2
## Cairo for ReportLab
#RUN apt install -y libcairo2-dev libjpeg8-dev libpng-dev
## Inkscape for editing and rendering
#RUN add-apt-repository ppa:inkscape.dev/stable && apt install -y inkscape
# Get requirements
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
# code base
COPY core core
COPY migrations migrations
COPY config.py .
COPY config.json .
ENV SERVER_MODE core


# api - flask backend api
FROM base AS api
# Get api files
COPY api api
COPY backend.py .
COPY boot.sh .
ENV FLASK_APP backend.py
ENV SERVER_MODE api
EXPOSE $PORT
CMD ["sh", "boot.sh"]


# host - use for globally-scoped processes like testing
FROM api AS host
ENV SERVER_MODE host
# Get the rest of the files
COPY tests tests


FROM host as locust
ENV SERVER_MODE locust
