# Multi-stage build for all images

# base - os and basic requirements
FROM python:3.9.7-slim-buster as base
# Apply global configs
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV SERVER_MODE base
WORKDIR /srv


# api - flask backend api
FROM base AS api
# Get api requirements
COPY api/requirements.txt .
RUN apt update && \
    apt install -y iputils-ping poppler-utils && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:inkscape.dev/stable \
    && apt-get install -y inkscape
RUN pip install --upgrade pip && pip install -r requirements.txt
# Get api files
COPY api api
COPY static static
COPY migrations migrations
COPY config.py .
COPY config.json .
COPY babel.cfg .
COPY backend.py .
COPY boot.sh .
ENV FLASK_APP backend.py
ENV SERVER_MODE api
EXPOSE $PORT
CMD ["sh", "boot.sh"]


# host - use for globally-scoped processes like testing
FROM api AS host
ENV SERVER_MODE host
# Get the rest of the files
COPY tests tests


FROM host as locust
ENV SERVER_MODE locust
