# Multi-stage build for all Luminary Handbook client images

FROM mhart/alpine-node:14 AS frontend-base
# install dependencies
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json /app/frontend/
# Copy all local files into the image.
COPY /frontend/src /app/frontend/src
COPY /frontend/docker.env /app/frontend/.env
COPY /frontend/static /app/frontend/static
COPY /frontend/jsconfig.json /app/frontend/jsconfig.json
COPY /frontend/svelte.config.js /app/frontend/svelte.config.js
#COPY /frontend/svelte.config.js /app/frontend/svelte.config.cjs
WORKDIR /app/frontend
RUN npm install
EXPOSE $PORT
ENV NODE_OPTIONS="--max-old-space-size=1024"
CMD ["npm", "run", "storybook"]
